### This loads all the CVRs for Demo1 - see README for details.

### 1. Adams County
### POST request with basic login.
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":"countyadmin1",
  "password":""
}

### POST request for second factor.
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":"countyadmin1",
  "second_factor":"s d f"
}

### GET the county dashboard.
GET http://localhost:8888/county-dashboard

### POST the cvr file and its hash
POST http://localhost:8888/upload-file
Content-Type: multipart/form-data; boundary=TheBoundary

--TheBoundary
Content-Disposition: form-data; name="file"; filename="1-adams-cvrexport-plusByron-1.csv"
Content-Type: text/csv

< ../resources/CSVs/Demo1/1-adams-cvrexport-plusByron-1.csv

--TheBoundary
Content-Disposition: form-data; name="hash"
Content-Type: text/csv

< ../resources/CSVs/Demo1/1-adams-cvrexport-plusByron-1.csv.sha256sum

### Request the CVR export to be imported
### TODO The ID must match the ID in the database, which gets returned in the upload to response.
### Timestamp doesn't seem to matter.
POST http://localhost:8888/import-cvr-export
Content-Type: application/json

{
  "approximateRecordCount":288,
  "countyId":1,
  "fileName":"1-adams-cvrexport-plusByron-1.csv",
  "hash":"225578912F620A42740B3EFE076E679BB3EE3E08CE70C6982EAF19D033D819BE",
  "id":433624,
  "result":{"success":false},
  "status":"HASH_VERIFIED",
  "size":64925,
  "timestamp":"2024-09-11T12:20:50.260106754Z"
}

### POST the manifest and its hash
POST http://localhost:8888/upload-file
Content-Type: multipart/form-data; boundary=TheBoundary

--TheBoundary
Content-Disposition: form-data; name="file"; filename="1-adams-plusByron-1-manifest.csv"
Content-Type: text/csv

< ../resources/CSVs/Demo1/1-adams-plusByron-1-manifest.csv

--TheBoundary
Content-Disposition: form-data; name="hash"
Content-Type: text/csv

< ../resources/CSVs/Demo1/1-adams-plusByron-1-manifest.csv.sha256sum

### Run import on ballot manifest
POST  http://localhost:8888/import-ballot-manifest
Content-Type: application/json

{
  "approximateRecordCount":8,
  "countyId":1,
  "fileName":"1-adams-plusByron-1-manifest.csv",
  "hash":"4EDBBC866D91D380CA83E02821056FCE49BF19F2C893C777CBFD3B17788EB366",
  "id":434641,
  "result":{"success":false},
  "status":"HASH_VERIFIED",
  "size":232,
  "timestamp":"2024-09-11T12:36:43.127325499Z"
}

