### This loads all the manifests for Demo1, except Boulder - see README for details.

### 1. Adams County, using 1-adams-cvrexport-plusByron-1.csv.
### POST request with basic login.
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":"countyadmin1",
  "password":""
}

### POST request for second factor.
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":"countyadmin1",
  "second_factor":"s d f"
}

### GET the county dashboard.
GET http://localhost:8888/county-dashboard

### POST the manifest and its hash
POST http://localhost:8888/upload-file
Content-Type: multipart/form-data; boundary=TheBoundary

--TheBoundary
Content-Disposition: form-data; name="file"; filename="1-adams-plusByron-1-manifest.csv"
Content-Type: text/csv

< ../resources/CSVs/Demo1/1-adams-plusByron-1-manifest.csv

--TheBoundary
Content-Disposition: form-data; name="hash"
Content-Type: text/csv

< ../resources/CSVs/Demo1/1-adams-plusByron-1-manifest.csv.sha256sum
--TheBoundary--

> {%
    const manifestUploadResponse = response.body;
    client.global.set("manifestUploadResponse", manifestUploadResponse)
%}

### Run import on ballot manifest
POST  http://localhost:8888/import-ballot-manifest
Content-Type: application/json

{{manifestUploadResponse}}

### Log out
POST http://localhost:8888/unauthenticate
Content-Type: application/json

{
  "username":"countyadmin1"
}

### 2. Alamosa County, using 2-alamosa-cvrexport-plusByron-2.csv
### POST request with basic login.
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":"countyadmin2",
  "password":""
}

### POST request for second factor.
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":"countyadmin2",
  "second_factor":"s d f"
}

### GET the county dashboard.
GET http://localhost:8888/county-dashboard

### POST the manifest and its hash
POST http://localhost:8888/upload-file
Content-Type: multipart/form-data; boundary=TheBoundary

--TheBoundary
Content-Disposition: form-data; name="file"; filename="2-alamosa-plusByron-2-manifest.csv"
Content-Type: text/csv

< ../resources/CSVs/Demo1/2-alamosa-plusByron-2-manifest.csv

--TheBoundary
Content-Disposition: form-data; name="hash"
Content-Type: text/csv

< ../resources/CSVs/Demo1/2-alamosa-plusByron-2-manifest.csv.sha256sum
--TheBoundary--

> {%
    const manifestUploadResponse = response.body;
    client.global.set("manifestUploadResponse", manifestUploadResponse)
%}

### Run import on ballot manifest
POST  http://localhost:8888/import-ballot-manifest
Content-Type: application/json

{{manifestUploadResponse}}

### Log out
POST http://localhost:8888/unauthenticate
Content-Type: application/json

{
  "username":"countyadmin2"
}

### 3. Arapahoe County, using 3-arapahoe-Byron-3-plus-tied-irv.csv
### POST request with basic login.
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":"countyadmin3",
  "password":""
}

### POST request for second factor.
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":"countyadmin3",
  "second_factor":"s d f"
}

### GET the county dashboard.
GET http://localhost:8888/county-dashboard

### POST the manifest and its hash
POST http://localhost:8888/upload-file
Content-Type: multipart/form-data; boundary=TheBoundary

--TheBoundary
Content-Disposition: form-data; name="file"; filename="Byron-3-manifest.csv"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-3-manifest.csv

--TheBoundary
Content-Disposition: form-data; name="hash"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-3-manifest.csv.sha256sum
--TheBoundary--

> {%
    const manifestUploadResponse = response.body;
    client.global.set("manifestUploadResponse", manifestUploadResponse)
%}

### Run import on ballot manifest
POST  http://localhost:8888/import-ballot-manifest
Content-Type: application/json

{{manifestUploadResponse}}

### Log out
POST http://localhost:8888/unauthenticate
Content-Type: application/json

{
  "username":"countyadmin3"
}

### 4. Archuleta County, using 4-archuleta-kempsey-plusByron-4.csv
### POST request with basic login.
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":"countyadmin4",
  "password":""
}

### POST request for second factor.
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":"countyadmin4",
  "second_factor":"s d f"
}

### GET the county dashboard.
GET http://localhost:8888/county-dashboard

### POST the manifest and its hash
POST http://localhost:8888/upload-file
Content-Type: multipart/form-data; boundary=TheBoundary

--TheBoundary
Content-Disposition: form-data; name="file"; filename="Kempsey_Mayoral.manifest.csv"
Content-Type: text/csv

< ../resources/CSVs/NewSouthWales21/Kempsey_Mayoral.manifest.csv

--TheBoundary
Content-Disposition: form-data; name="hash"
Content-Type: text/csv

< ../resources/CSVs/NewSouthWales21/Kempsey_Mayoral.manifest.csv.sha256sum
--TheBoundary--

> {%
    const manifestUploadResponse = response.body;
    client.global.set("manifestUploadResponse", manifestUploadResponse)
%}

### Run import on ballot manifest
POST  http://localhost:8888/import-ballot-manifest
Content-Type: application/json

{{manifestUploadResponse}}

### Log out
POST http://localhost:8888/unauthenticate
Content-Type: application/json

{
  "username":"countyadmin4"
}

### Now run counties n = 5..64, except 7 (Boulder) which is done separately, uploading split-Byron-n for each.
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":"countyadmin5",
  "password":""
}

### POST request for second factor.
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":"countyadmin5",
  "second_factor":"s d f"
}

### GET the county dashboard.
GET http://localhost:8888/county-dashboard

### POST the manifest and its hash
POST http://localhost:8888/upload-file
Content-Type: multipart/form-data; boundary=TheBoundary

--TheBoundary
Content-Disposition: form-data; name="file"; filename="Byron-5-manifest.csv"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-5-manifest.csv

--TheBoundary
Content-Disposition: form-data; name="hash"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-5-manifest.csv.sha256sum
--TheBoundary--

> {%
    const manifestUploadResponse = response.body;
    client.global.set("manifestUploadResponse", manifestUploadResponse)
%}

### Run import on ballot manifest
POST  http://localhost:8888/import-ballot-manifest
Content-Type: application/json

{{manifestUploadResponse}}

### Log out
POST http://localhost:8888/unauthenticate
Content-Type: application/json

{
  "username":"countyadmin5"
}

### Now county 6
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
"username":"countyadmin6",
"password":""
}

### POST request for second factor.
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":"countyadmin6",
  "second_factor":"s d f"
}

### GET the county dashboard.
GET http://localhost:8888/county-dashboard

### POST the manifest and its hash
POST http://localhost:8888/upload-file
Content-Type: multipart/form-data; boundary=TheBoundary

--TheBoundary
Content-Disposition: form-data; name="file"; filename="Byron-6-manifest.csv"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-6-manifest.csv

--TheBoundary
Content-Disposition: form-data; name="hash"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-6-manifest.csv.sha256sum
--TheBoundary--

> {%
    const manifestUploadResponse = response.body;
    client.global.set("manifestUploadResponse", manifestUploadResponse)
%}

### Run import on ballot manifest
POST  http://localhost:8888/import-ballot-manifest
Content-Type: application/json

{{manifestUploadResponse}}

### Log out
POST http://localhost:8888/unauthenticate
Content-Type: application/json

{
  "username":"countyadmin6"
}

### Now county 8 - note we skipped 7 (Boulder)
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":"countyadmin8",
  "password":""
}

### POST request for second factor.
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":"countyadmin8",
  "second_factor":"s d f"
}

### GET the county dashboard.
GET http://localhost:8888/county-dashboard

### POST the manifest and its hash
POST http://localhost:8888/upload-file
Content-Type: multipart/form-data; boundary=TheBoundary

--TheBoundary
Content-Disposition: form-data; name="file"; filename="Byron-8-manifest.csv"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-8-manifest.csv

--TheBoundary
Content-Disposition: form-data; name="hash"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-8-manifest.csv.sha256sum
--TheBoundary--

> {%
    const manifestUploadResponse = response.body;
    client.global.set("manifestUploadResponse", manifestUploadResponse)
%}

### Run import on ballot manifest
POST  http://localhost:8888/import-ballot-manifest
Content-Type: application/json

{{manifestUploadResponse}}

### Log out
POST http://localhost:8888/unauthenticate
Content-Type: application/json

{
  "username":"countyadmin8"
}

### Now county 9
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":"countyadmin9",
  "password":""
}

> {%
    client.global.set("countyUsername", "countyadmin9")
%}


### POST request for second factor.
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":{{countyUsername}},
  "second_factor":"s d f"
}

### GET the county dashboard.
GET http://localhost:8888/county-dashboard

### POST the manifest and its hash
POST http://localhost:8888/upload-file
Content-Type: multipart/form-data; boundary=TheBoundary

--TheBoundary
Content-Disposition: form-data; name="file"; filename="Byron-9-manifest.csv"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-9-manifest.csv

--TheBoundary
Content-Disposition: form-data; name="hash"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-9-manifest.csv.sha256sum
--TheBoundary--

> {%
    const manifestUploadResponse = response.body;
    client.global.set("manifestUploadResponse", manifestUploadResponse)
%}

### Run import on ballot manifest
POST  http://localhost:8888/import-ballot-manifest
Content-Type: application/json

{{manifestUploadResponse}}

### Log out
POST http://localhost:8888/unauthenticate
Content-Type: application/json

{
  "username":{{countyUsername}}
}

### Now county 10
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":"countyadmin10",
  "password":""
}

> {%
    client.global.set("countyUsername", "countyadmin10")
%}


### POST request for second factor.
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":{{countyUsername}},
  "second_factor":"s d f"
}

### GET the county dashboard.
GET http://localhost:8888/county-dashboard

### POST the manifest and its hash
POST http://localhost:8888/upload-file
Content-Type: multipart/form-data; boundary=TheBoundary

--TheBoundary
Content-Disposition: form-data; name="file"; filename="Byron-10-manifest.csv"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-10-manifest.csv

--TheBoundary
Content-Disposition: form-data; name="hash"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-10-manifest.csv.sha256sum
--TheBoundary--

> {%
    const manifestUploadResponse = response.body;
    client.global.set("manifestUploadResponse", manifestUploadResponse)
%}

### Run import on ballot manifest
POST  http://localhost:8888/import-ballot-manifest
Content-Type: application/json

{{manifestUploadResponse}}

### Log out
POST http://localhost:8888/unauthenticate
Content-Type: application/json

{
  "username":{{countyUsername}}
}

### Now county 11
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":"countyadmin11",
  "password":""
}

> {%
    client.global.set("countyUsername", "countyadmin11")
%}


### POST request for second factor.
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":{{countyUsername}},
  "second_factor":"s d f"
}

### GET the county dashboard.
GET http://localhost:8888/county-dashboard

### POST the manifest and its hash
POST http://localhost:8888/upload-file
Content-Type: multipart/form-data; boundary=TheBoundary

--TheBoundary
Content-Disposition: form-data; name="file"; filename="Byron-11-manifest.csv"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-11-manifest.csv

--TheBoundary
Content-Disposition: form-data; name="hash"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-11-manifest.csv.sha256sum
--TheBoundary--

> {%
    const manifestUploadResponse = response.body;
    client.global.set("manifestUploadResponse", manifestUploadResponse)
%}

### Run import on ballot manifest
POST  http://localhost:8888/import-ballot-manifest
Content-Type: application/json

{{manifestUploadResponse}}

### Log out
POST http://localhost:8888/unauthenticate
Content-Type: application/json

{
  "username":{{countyUsername}}
}

### Now county 12
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":"countyadmin12",
  "password":""
}

> {%
    client.global.set("countyUsername", "countyadmin12")
%}


### POST request for second factor.
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":{{countyUsername}},
  "second_factor":"s d f"
}

### GET the county dashboard.
GET http://localhost:8888/county-dashboard

### POST the manifest and its hash
POST http://localhost:8888/upload-file
Content-Type: multipart/form-data; boundary=TheBoundary

--TheBoundary
Content-Disposition: form-data; name="file"; filename="Byron-12-manifest.csv"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-12-manifest.csv

--TheBoundary
Content-Disposition: form-data; name="hash"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-12-manifest.csv.sha256sum
--TheBoundary--

> {%
    const manifestUploadResponse = response.body;
    client.global.set("manifestUploadResponse", manifestUploadResponse)
%}

### Run import on ballot manifest
POST  http://localhost:8888/import-ballot-manifest
Content-Type: application/json

{{manifestUploadResponse}}

### Log out
POST http://localhost:8888/unauthenticate
Content-Type: application/json

{
  "username":{{countyUsername}}
}

### Now county 13
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":"countyadmin13",
  "password":""
}

> {%
    client.global.set("countyUsername", "countyadmin13")
%}


### POST request for second factor.
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":{{countyUsername}},
  "second_factor":"s d f"
}

### GET the county dashboard.
GET http://localhost:8888/county-dashboard

### POST the manifest and its hash
POST http://localhost:8888/upload-file
Content-Type: multipart/form-data; boundary=TheBoundary

--TheBoundary
Content-Disposition: form-data; name="file"; filename="Byron-13-manifest.csv"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-13-manifest.csv

--TheBoundary
Content-Disposition: form-data; name="hash"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-13-manifest.csv.sha256sum
--TheBoundary--

> {%
    const manifestUploadResponse = response.body;
    client.global.set("manifestUploadResponse", manifestUploadResponse)
%}

### Run import on ballot manifest
POST  http://localhost:8888/import-ballot-manifest
Content-Type: application/json

{{manifestUploadResponse}}

### Log out
POST http://localhost:8888/unauthenticate
Content-Type: application/json

{
  "username":{{countyUsername}}
}

### Now county 14
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":"countyadmin14",
  "password":""
}

> {%
    client.global.set("countyUsername", "countyadmin14")
%}


### POST request for second factor.
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":{{countyUsername}},
  "second_factor":"s d f"
}

### GET the county dashboard.
GET http://localhost:8888/county-dashboard

### POST the manifest and its hash
POST http://localhost:8888/upload-file
Content-Type: multipart/form-data; boundary=TheBoundary

--TheBoundary
Content-Disposition: form-data; name="file"; filename="Byron-14-manifest.csv"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-14-manifest.csv

--TheBoundary
Content-Disposition: form-data; name="hash"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-14-manifest.csv.sha256sum
--TheBoundary--

> {%
    const manifestUploadResponse = response.body;
    client.global.set("manifestUploadResponse", manifestUploadResponse)
%}

### Run import on ballot manifest
POST  http://localhost:8888/import-ballot-manifest
Content-Type: application/json

{{manifestUploadResponse}}

### Log out
POST http://localhost:8888/unauthenticate
Content-Type: application/json

{
  "username":{{countyUsername}}
}

### Now county 15
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":"countyadmin15",
  "password":""
}

> {%
    client.global.set("countyUsername", "countyadmin15")
%}


### POST request for second factor.
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":{{countyUsername}},
  "second_factor":"s d f"
}

### GET the county dashboard.
GET http://localhost:8888/county-dashboard

### POST the manifest and its hash
POST http://localhost:8888/upload-file
Content-Type: multipart/form-data; boundary=TheBoundary

--TheBoundary
Content-Disposition: form-data; name="file"; filename="Byron-15-manifest.csv"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-15-manifest.csv

--TheBoundary
Content-Disposition: form-data; name="hash"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-15-manifest.csv.sha256sum
--TheBoundary--

> {%
    const manifestUploadResponse = response.body;
    client.global.set("manifestUploadResponse", manifestUploadResponse)
%}

### Run import on ballot manifest
POST  http://localhost:8888/import-ballot-manifest
Content-Type: application/json

{{manifestUploadResponse}}

### Log out
POST http://localhost:8888/unauthenticate
Content-Type: application/json

{
  "username":{{countyUsername}}
}

### Now county 16
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":"countyadmin16",
  "password":""
}

> {%
    client.global.set("countyUsername", "countyadmin16")
%}


### POST request for second factor.
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":{{countyUsername}},
  "second_factor":"s d f"
}

### GET the county dashboard.
GET http://localhost:8888/county-dashboard

### POST the manifest and its hash
POST http://localhost:8888/upload-file
Content-Type: multipart/form-data; boundary=TheBoundary

--TheBoundary
Content-Disposition: form-data; name="file"; filename="Byron-16-manifest.csv"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-16-manifest.csv

--TheBoundary
Content-Disposition: form-data; name="hash"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-16-manifest.csv.sha256sum
--TheBoundary--

> {%
    const manifestUploadResponse = response.body;
    client.global.set("manifestUploadResponse", manifestUploadResponse)
%}

### Run import on ballot manifest
POST  http://localhost:8888/import-ballot-manifest
Content-Type: application/json

{{manifestUploadResponse}}

### Log out
POST http://localhost:8888/unauthenticate
Content-Type: application/json

{
  "username":{{countyUsername}}
}

### Now county 17
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":"countyadmin17",
  "password":""
}

> {%
    client.global.set("countyUsername", "countyadmin17")
%}


### POST request for second factor.
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":{{countyUsername}},
  "second_factor":"s d f"
}

### GET the county dashboard.
GET http://localhost:8888/county-dashboard

### POST the manifest and its hash
POST http://localhost:8888/upload-file
Content-Type: multipart/form-data; boundary=TheBoundary

--TheBoundary
Content-Disposition: form-data; name="file"; filename="Byron-17-manifest.csv"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-17-manifest.csv

--TheBoundary
Content-Disposition: form-data; name="hash"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-17-manifest.csv.sha256sum
--TheBoundary--

> {%
    const manifestUploadResponse = response.body;
    client.global.set("manifestUploadResponse", manifestUploadResponse)
%}

### Run import on ballot manifest
POST  http://localhost:8888/import-ballot-manifest
Content-Type: application/json

{{manifestUploadResponse}}

### Log out
POST http://localhost:8888/unauthenticate
Content-Type: application/json

{
  "username":{{countyUsername}}
}

### Now county 18
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":"countyadmin18",
  "password":""
}

> {%
    client.global.set("countyUsername", "countyadmin18")
%}


### POST request for second factor.
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":{{countyUsername}},
  "second_factor":"s d f"
}

### GET the county dashboard.
GET http://localhost:8888/county-dashboard

### POST the manifest and its hash
POST http://localhost:8888/upload-file
Content-Type: multipart/form-data; boundary=TheBoundary

--TheBoundary
Content-Disposition: form-data; name="file"; filename="Byron-18-manifest.csv"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-18-manifest.csv

--TheBoundary
Content-Disposition: form-data; name="hash"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-18-manifest.csv.sha256sum
--TheBoundary--

> {%
    const manifestUploadResponse = response.body;
    client.global.set("manifestUploadResponse", manifestUploadResponse)
%}

### Run import on ballot manifest
POST  http://localhost:8888/import-ballot-manifest
Content-Type: application/json

{{manifestUploadResponse}}

### Log out
POST http://localhost:8888/unauthenticate
Content-Type: application/json

{
  "username":{{countyUsername}}
}

### Now county 19
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":"countyadmin19",
  "password":""
}

> {%
    client.global.set("countyUsername", "countyadmin19")
%}


### POST request for second factor.
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":{{countyUsername}},
  "second_factor":"s d f"
}

### GET the county dashboard.
GET http://localhost:8888/county-dashboard

### POST the manifest and its hash
POST http://localhost:8888/upload-file
Content-Type: multipart/form-data; boundary=TheBoundary

--TheBoundary
Content-Disposition: form-data; name="file"; filename="Byron-19-manifest.csv"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-19-manifest.csv

--TheBoundary
Content-Disposition: form-data; name="hash"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-19-manifest.csv.sha256sum
--TheBoundary--

> {%
    const manifestUploadResponse = response.body;
    client.global.set("manifestUploadResponse", manifestUploadResponse)
%}

### Run import on ballot manifest
POST  http://localhost:8888/import-ballot-manifest
Content-Type: application/json

{{manifestUploadResponse}}

### Log out
POST http://localhost:8888/unauthenticate
Content-Type: application/json

{
  "username":{{countyUsername}}
}

### Now county 20
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":"countyadmin20",
  "password":""
}

> {%
    client.global.set("countyUsername", "countyadmin20")
%}


### POST request for second factor.
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":{{countyUsername}},
  "second_factor":"s d f"
}

### GET the county dashboard.
GET http://localhost:8888/county-dashboard

### POST the manifest and its hash
POST http://localhost:8888/upload-file
Content-Type: multipart/form-data; boundary=TheBoundary

--TheBoundary
Content-Disposition: form-data; name="file"; filename="Byron-20-manifest.csv"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-20-manifest.csv

--TheBoundary
Content-Disposition: form-data; name="hash"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-20-manifest.csv.sha256sum
--TheBoundary--

> {%
    const manifestUploadResponse = response.body;
    client.global.set("manifestUploadResponse", manifestUploadResponse)
%}

### Run import on ballot manifest
POST  http://localhost:8888/import-ballot-manifest
Content-Type: application/json

{{manifestUploadResponse}}

### Log out
POST http://localhost:8888/unauthenticate
Content-Type: application/json

{
  "username":{{countyUsername}}
}

### Now county 21
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":"countyadmin21",
  "password":""
}

> {%
    client.global.set("countyUsername", "countyadmin21")
%}


### POST request for second factor.
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":{{countyUsername}},
  "second_factor":"s d f"
}

### GET the county dashboard.
GET http://localhost:8888/county-dashboard

### POST the manifest and its hash
POST http://localhost:8888/upload-file
Content-Type: multipart/form-data; boundary=TheBoundary

--TheBoundary
Content-Disposition: form-data; name="file"; filename="Byron-21-manifest.csv"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-21-manifest.csv

--TheBoundary
Content-Disposition: form-data; name="hash"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-21-manifest.csv.sha256sum
--TheBoundary--

> {%
    const manifestUploadResponse = response.body;
    client.global.set("manifestUploadResponse", manifestUploadResponse)
%}

### Run import on ballot manifest
POST  http://localhost:8888/import-ballot-manifest
Content-Type: application/json

{{manifestUploadResponse}}

### Log out
POST http://localhost:8888/unauthenticate
Content-Type: application/json

{
  "username":{{countyUsername}}
}

### Now county 22
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":"countyadmin22",
  "password":""
}

> {%
    client.global.set("countyUsername", "countyadmin22")
%}


### POST request for second factor.
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":{{countyUsername}},
  "second_factor":"s d f"
}

### GET the county dashboard.
GET http://localhost:8888/county-dashboard

### POST the manifest and its hash
POST http://localhost:8888/upload-file
Content-Type: multipart/form-data; boundary=TheBoundary

--TheBoundary
Content-Disposition: form-data; name="file"; filename="Byron-22-manifest.csv"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-22-manifest.csv

--TheBoundary
Content-Disposition: form-data; name="hash"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-22-manifest.csv.sha256sum
--TheBoundary--

> {%
    const manifestUploadResponse = response.body;
    client.global.set("manifestUploadResponse", manifestUploadResponse)
%}

### Run import on ballot manifest
POST  http://localhost:8888/import-ballot-manifest
Content-Type: application/json

{{manifestUploadResponse}}

### Log out
POST http://localhost:8888/unauthenticate
Content-Type: application/json

{
  "username":{{countyUsername}}
}

### Now county 23
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":"countyadmin23",
  "password":""
}

> {%
    client.global.set("countyUsername", "countyadmin23")
%}


### POST request for second factor.
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":{{countyUsername}},
  "second_factor":"s d f"
}

### GET the county dashboard.
GET http://localhost:8888/county-dashboard

### POST the manifest and its hash
POST http://localhost:8888/upload-file
Content-Type: multipart/form-data; boundary=TheBoundary

--TheBoundary
Content-Disposition: form-data; name="file"; filename="Byron-23-manifest.csv"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-23-manifest.csv

--TheBoundary
Content-Disposition: form-data; name="hash"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-23-manifest.csv.sha256sum
--TheBoundary--

> {%
    const manifestUploadResponse = response.body;
    client.global.set("manifestUploadResponse", manifestUploadResponse)
%}

### Run import on ballot manifest
POST  http://localhost:8888/import-ballot-manifest
Content-Type: application/json

{{manifestUploadResponse}}

### Log out
POST http://localhost:8888/unauthenticate
Content-Type: application/json

{
  "username":{{countyUsername}}
}

### Now county 24
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":"countyadmin24",
  "password":""
}

> {%
    client.global.set("countyUsername", "countyadmin24")
%}


### POST request for second factor.
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":{{countyUsername}},
  "second_factor":"s d f"
}

### GET the county dashboard.
GET http://localhost:8888/county-dashboard

### POST the manifest and its hash
POST http://localhost:8888/upload-file
Content-Type: multipart/form-data; boundary=TheBoundary

--TheBoundary
Content-Disposition: form-data; name="file"; filename="Byron-24-manifest.csv"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-24-manifest.csv

--TheBoundary
Content-Disposition: form-data; name="hash"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-24-manifest.csv.sha256sum
--TheBoundary--

> {%
    const manifestUploadResponse = response.body;
    client.global.set("manifestUploadResponse", manifestUploadResponse)
%}

### Run import on ballot manifest
POST  http://localhost:8888/import-ballot-manifest
Content-Type: application/json

{{manifestUploadResponse}}

### Log out
POST http://localhost:8888/unauthenticate
Content-Type: application/json

{
  "username":{{countyUsername}}
}

### Now county 25
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":"countyadmin25",
  "password":""
}

> {%
    client.global.set("countyUsername", "countyadmin25")
%}


### POST request for second factor.
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":{{countyUsername}},
  "second_factor":"s d f"
}

### GET the county dashboard.
GET http://localhost:8888/county-dashboard

### POST the manifest and its hash
POST http://localhost:8888/upload-file
Content-Type: multipart/form-data; boundary=TheBoundary

--TheBoundary
Content-Disposition: form-data; name="file"; filename="Byron-25-manifest.csv"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-25-manifest.csv

--TheBoundary
Content-Disposition: form-data; name="hash"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-25-manifest.csv.sha256sum
--TheBoundary--

> {%
    const manifestUploadResponse = response.body;
    client.global.set("manifestUploadResponse", manifestUploadResponse)
%}

### Run import on ballot manifest
POST  http://localhost:8888/import-ballot-manifest
Content-Type: application/json

{{manifestUploadResponse}}

### Log out
POST http://localhost:8888/unauthenticate
Content-Type: application/json

{
  "username":{{countyUsername}}
}

### Now county 26
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":"countyadmin26",
  "password":""
}

> {%
    client.global.set("countyUsername", "countyadmin26")
%}


### POST request for second factor.
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":{{countyUsername}},
  "second_factor":"s d f"
}

### GET the county dashboard.
GET http://localhost:8888/county-dashboard

### POST the manifest and its hash
POST http://localhost:8888/upload-file
Content-Type: multipart/form-data; boundary=TheBoundary

--TheBoundary
Content-Disposition: form-data; name="file"; filename="Byron-26-manifest.csv"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-26-manifest.csv

--TheBoundary
Content-Disposition: form-data; name="hash"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-26-manifest.csv.sha256sum
--TheBoundary--

> {%
    const manifestUploadResponse = response.body;
    client.global.set("manifestUploadResponse", manifestUploadResponse)
%}

### Run import on ballot manifest
POST  http://localhost:8888/import-ballot-manifest
Content-Type: application/json

{{manifestUploadResponse}}

### Log out
POST http://localhost:8888/unauthenticate
Content-Type: application/json

{
  "username":{{countyUsername}}
}

### Now county 27
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":"countyadmin27",
  "password":""
}

> {%
    client.global.set("countyUsername", "countyadmin27")
%}


### POST request for second factor.
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":{{countyUsername}},
  "second_factor":"s d f"
}

### GET the county dashboard.
GET http://localhost:8888/county-dashboard

### POST the manifest and its hash
POST http://localhost:8888/upload-file
Content-Type: multipart/form-data; boundary=TheBoundary

--TheBoundary
Content-Disposition: form-data; name="file"; filename="Byron-27-manifest.csv"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-27-manifest.csv

--TheBoundary
Content-Disposition: form-data; name="hash"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-27-manifest.csv.sha256sum
--TheBoundary--

> {%
    const manifestUploadResponse = response.body;
    client.global.set("manifestUploadResponse", manifestUploadResponse)
%}

### Run import on ballot manifest
POST  http://localhost:8888/import-ballot-manifest
Content-Type: application/json

{{manifestUploadResponse}}

### Log out
POST http://localhost:8888/unauthenticate
Content-Type: application/json

{
  "username":{{countyUsername}}
}

### Now county 28
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":"countyadmin28",
  "password":""
}

> {%
    client.global.set("countyUsername", "countyadmin28")
%}


### POST request for second factor.
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":{{countyUsername}},
  "second_factor":"s d f"
}

### GET the county dashboard.
GET http://localhost:8888/county-dashboard

### POST the manifest and its hash
POST http://localhost:8888/upload-file
Content-Type: multipart/form-data; boundary=TheBoundary

--TheBoundary
Content-Disposition: form-data; name="file"; filename="Byron-28-manifest.csv"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-28-manifest.csv

--TheBoundary
Content-Disposition: form-data; name="hash"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-28-manifest.csv.sha256sum
--TheBoundary--

> {%
    const manifestUploadResponse = response.body;
    client.global.set("manifestUploadResponse", manifestUploadResponse)
%}

### Run import on ballot manifest
POST  http://localhost:8888/import-ballot-manifest
Content-Type: application/json

{{manifestUploadResponse}}

### Log out
POST http://localhost:8888/unauthenticate
Content-Type: application/json

{
  "username":{{countyUsername}}
}

### Now county 29
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":"countyadmin29",
  "password":""
}

> {%
    client.global.set("countyUsername", "countyadmin29")
%}


### POST request for second factor.
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":{{countyUsername}},
  "second_factor":"s d f"
}

### GET the county dashboard.
GET http://localhost:8888/county-dashboard

### POST the manifest and its hash
POST http://localhost:8888/upload-file
Content-Type: multipart/form-data; boundary=TheBoundary

--TheBoundary
Content-Disposition: form-data; name="file"; filename="Byron-29-manifest.csv"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-29-manifest.csv

--TheBoundary
Content-Disposition: form-data; name="hash"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-29-manifest.csv.sha256sum
--TheBoundary--

> {%
    const manifestUploadResponse = response.body;
    client.global.set("manifestUploadResponse", manifestUploadResponse)
%}

### Run import on ballot manifest
POST  http://localhost:8888/import-ballot-manifest
Content-Type: application/json

{{manifestUploadResponse}}

### Log out
POST http://localhost:8888/unauthenticate
Content-Type: application/json

{
  "username":{{countyUsername}}
}

### Now county 30
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":"countyadmin30",
  "password":""
}

> {%
    client.global.set("countyUsername", "countyadmin30")
%}


### POST request for second factor.
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":{{countyUsername}},
  "second_factor":"s d f"
}

### GET the county dashboard.
GET http://localhost:8888/county-dashboard

### POST the manifest and its hash
POST http://localhost:8888/upload-file
Content-Type: multipart/form-data; boundary=TheBoundary

--TheBoundary
Content-Disposition: form-data; name="file"; filename="Byron-30-manifest.csv"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-30-manifest.csv

--TheBoundary
Content-Disposition: form-data; name="hash"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-30-manifest.csv.sha256sum
--TheBoundary--

> {%
    const manifestUploadResponse = response.body;
    client.global.set("manifestUploadResponse", manifestUploadResponse)
%}

### Run import on ballot manifest
POST  http://localhost:8888/import-ballot-manifest
Content-Type: application/json

{{manifestUploadResponse}}

### Log out
POST http://localhost:8888/unauthenticate
Content-Type: application/json

{
  "username":{{countyUsername}}
}

### Now county 31
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":"countyadmin31",
  "password":""
}

> {%
    client.global.set("countyUsername", "countyadmin31")
%}


### POST request for second factor.
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":{{countyUsername}},
  "second_factor":"s d f"
}

### GET the county dashboard.
GET http://localhost:8888/county-dashboard

### POST the manifest and its hash
POST http://localhost:8888/upload-file
Content-Type: multipart/form-data; boundary=TheBoundary

--TheBoundary
Content-Disposition: form-data; name="file"; filename="Byron-31-manifest.csv"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-31-manifest.csv

--TheBoundary
Content-Disposition: form-data; name="hash"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-31-manifest.csv.sha256sum
--TheBoundary--

> {%
    const manifestUploadResponse = response.body;
    client.global.set("manifestUploadResponse", manifestUploadResponse)
%}

### Run import on ballot manifest
POST  http://localhost:8888/import-ballot-manifest
Content-Type: application/json

{{manifestUploadResponse}}

### Log out
POST http://localhost:8888/unauthenticate
Content-Type: application/json

{
  "username":{{countyUsername}}
}

### Now county 32
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":"countyadmin32",
  "password":""
}

> {%
    client.global.set("countyUsername", "countyadmin32")
%}


### POST request for second factor.
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":{{countyUsername}},
  "second_factor":"s d f"
}

### GET the county dashboard.
GET http://localhost:8888/county-dashboard

### POST the manifest and its hash
POST http://localhost:8888/upload-file
Content-Type: multipart/form-data; boundary=TheBoundary

--TheBoundary
Content-Disposition: form-data; name="file"; filename="Byron-32-manifest.csv"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-32-manifest.csv

--TheBoundary
Content-Disposition: form-data; name="hash"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-32-manifest.csv.sha256sum
--TheBoundary--

> {%
    const manifestUploadResponse = response.body;
    client.global.set("manifestUploadResponse", manifestUploadResponse)
%}

### Run import on ballot manifest
POST  http://localhost:8888/import-ballot-manifest
Content-Type: application/json

{{manifestUploadResponse}}

### Log out
POST http://localhost:8888/unauthenticate
Content-Type: application/json

{
  "username":{{countyUsername}}
}

### Now county 33
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":"countyadmin33",
  "password":""
}

> {%
    client.global.set("countyUsername", "countyadmin33")
%}


### POST request for second factor.
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":{{countyUsername}},
  "second_factor":"s d f"
}

### GET the county dashboard.
GET http://localhost:8888/county-dashboard

### POST the manifest and its hash
POST http://localhost:8888/upload-file
Content-Type: multipart/form-data; boundary=TheBoundary

--TheBoundary
Content-Disposition: form-data; name="file"; filename="Byron-33-manifest.csv"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-33-manifest.csv

--TheBoundary
Content-Disposition: form-data; name="hash"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-33-manifest.csv.sha256sum
--TheBoundary--

> {%
    const manifestUploadResponse = response.body;
    client.global.set("manifestUploadResponse", manifestUploadResponse)
%}

### Run import on ballot manifest
POST  http://localhost:8888/import-ballot-manifest
Content-Type: application/json

{{manifestUploadResponse}}

### Log out
POST http://localhost:8888/unauthenticate
Content-Type: application/json

{
  "username":{{countyUsername}}
}

### Now county 34
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":"countyadmin34",
  "password":""
}

> {%
    client.global.set("countyUsername", "countyadmin34")
%}


### POST request for second factor.
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":{{countyUsername}},
  "second_factor":"s d f"
}

### GET the county dashboard.
GET http://localhost:8888/county-dashboard

### POST the manifest and its hash
POST http://localhost:8888/upload-file
Content-Type: multipart/form-data; boundary=TheBoundary

--TheBoundary
Content-Disposition: form-data; name="file"; filename="Byron-34-manifest.csv"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-34-manifest.csv

--TheBoundary
Content-Disposition: form-data; name="hash"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-34-manifest.csv.sha256sum
--TheBoundary--

> {%
    const manifestUploadResponse = response.body;
    client.global.set("manifestUploadResponse", manifestUploadResponse)
%}

### Run import on ballot manifest
POST  http://localhost:8888/import-ballot-manifest
Content-Type: application/json

{{manifestUploadResponse}}

### Log out
POST http://localhost:8888/unauthenticate
Content-Type: application/json

{
  "username":{{countyUsername}}
}

### Now county 35
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":"countyadmin35",
  "password":""
}

> {%
    client.global.set("countyUsername", "countyadmin35")
%}


### POST request for second factor.
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":{{countyUsername}},
  "second_factor":"s d f"
}

### GET the county dashboard.
GET http://localhost:8888/county-dashboard

### POST the manifest and its hash
POST http://localhost:8888/upload-file
Content-Type: multipart/form-data; boundary=TheBoundary

--TheBoundary
Content-Disposition: form-data; name="file"; filename="Byron-35-manifest.csv"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-35-manifest.csv

--TheBoundary
Content-Disposition: form-data; name="hash"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-35-manifest.csv.sha256sum
--TheBoundary--

> {%
    const manifestUploadResponse = response.body;
    client.global.set("manifestUploadResponse", manifestUploadResponse)
%}

### Run import on ballot manifest
POST  http://localhost:8888/import-ballot-manifest
Content-Type: application/json

{{manifestUploadResponse}}

### Log out
POST http://localhost:8888/unauthenticate
Content-Type: application/json

{
  "username":{{countyUsername}}
}

### Now county 36
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":"countyadmin36",
  "password":""
}

> {%
    client.global.set("countyUsername", "countyadmin36")
%}


### POST request for second factor.
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":{{countyUsername}},
  "second_factor":"s d f"
}

### GET the county dashboard.
GET http://localhost:8888/county-dashboard

### POST the manifest and its hash
POST http://localhost:8888/upload-file
Content-Type: multipart/form-data; boundary=TheBoundary

--TheBoundary
Content-Disposition: form-data; name="file"; filename="Byron-36-manifest.csv"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-36-manifest.csv

--TheBoundary
Content-Disposition: form-data; name="hash"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-36-manifest.csv.sha256sum
--TheBoundary--

> {%
    const manifestUploadResponse = response.body;
    client.global.set("manifestUploadResponse", manifestUploadResponse)
%}

### Run import on ballot manifest
POST  http://localhost:8888/import-ballot-manifest
Content-Type: application/json

{{manifestUploadResponse}}

### Log out
POST http://localhost:8888/unauthenticate
Content-Type: application/json

{
  "username":{{countyUsername}}
}

### Now county 37
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":"countyadmin37",
  "password":""
}

> {%
    client.global.set("countyUsername", "countyadmin37")
%}


### POST request for second factor.
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":{{countyUsername}},
  "second_factor":"s d f"
}

### GET the county dashboard.
GET http://localhost:8888/county-dashboard

### POST the manifest and its hash
POST http://localhost:8888/upload-file
Content-Type: multipart/form-data; boundary=TheBoundary

--TheBoundary
Content-Disposition: form-data; name="file"; filename="Byron-37-manifest.csv"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-37-manifest.csv

--TheBoundary
Content-Disposition: form-data; name="hash"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-37-manifest.csv.sha256sum
--TheBoundary--

> {%
    const manifestUploadResponse = response.body;
    client.global.set("manifestUploadResponse", manifestUploadResponse)
%}

### Run import on ballot manifest
POST  http://localhost:8888/import-ballot-manifest
Content-Type: application/json

{{manifestUploadResponse}}

### Log out
POST http://localhost:8888/unauthenticate
Content-Type: application/json

{
  "username":{{countyUsername}}
}

### Now county 38
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":"countyadmin38",
  "password":""
}

> {%
    client.global.set("countyUsername", "countyadmin38")
%}


### POST request for second factor.
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":{{countyUsername}},
  "second_factor":"s d f"
}

### GET the county dashboard.
GET http://localhost:8888/county-dashboard

### POST the manifest and its hash
POST http://localhost:8888/upload-file
Content-Type: multipart/form-data; boundary=TheBoundary

--TheBoundary
Content-Disposition: form-data; name="file"; filename="Byron-38-manifest.csv"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-38-manifest.csv

--TheBoundary
Content-Disposition: form-data; name="hash"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-38-manifest.csv.sha256sum
--TheBoundary--

> {%
    const manifestUploadResponse = response.body;
    client.global.set("manifestUploadResponse", manifestUploadResponse)
%}

### Run import on ballot manifest
POST  http://localhost:8888/import-ballot-manifest
Content-Type: application/json

{{manifestUploadResponse}}

### Log out
POST http://localhost:8888/unauthenticate
Content-Type: application/json

{
  "username":{{countyUsername}}
}

### Now county 39
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":"countyadmin39",
  "password":""
}

> {%
    client.global.set("countyUsername", "countyadmin39")
%}


### POST request for second factor.
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":{{countyUsername}},
  "second_factor":"s d f"
}

### GET the county dashboard.
GET http://localhost:8888/county-dashboard

### POST the manifest and its hash
POST http://localhost:8888/upload-file
Content-Type: multipart/form-data; boundary=TheBoundary

--TheBoundary
Content-Disposition: form-data; name="file"; filename="Byron-39-manifest.csv"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-39-manifest.csv

--TheBoundary
Content-Disposition: form-data; name="hash"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-39-manifest.csv.sha256sum
--TheBoundary--

> {%
    const manifestUploadResponse = response.body;
    client.global.set("manifestUploadResponse", manifestUploadResponse)
%}

### Run import on ballot manifest
POST  http://localhost:8888/import-ballot-manifest
Content-Type: application/json

{{manifestUploadResponse}}

### Log out
POST http://localhost:8888/unauthenticate
Content-Type: application/json

{
  "username":{{countyUsername}}
}

### Now county 40
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":"countyadmin40",
  "password":""
}

> {%
    client.global.set("countyUsername", "countyadmin40")
%}


### POST request for second factor.
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":{{countyUsername}},
  "second_factor":"s d f"
}

### GET the county dashboard.
GET http://localhost:8888/county-dashboard

### POST the manifest and its hash
POST http://localhost:8888/upload-file
Content-Type: multipart/form-data; boundary=TheBoundary

--TheBoundary
Content-Disposition: form-data; name="file"; filename="Byron-40-manifest.csv"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-40-manifest.csv

--TheBoundary
Content-Disposition: form-data; name="hash"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-40-manifest.csv.sha256sum
--TheBoundary--

> {%
    const manifestUploadResponse = response.body;
    client.global.set("manifestUploadResponse", manifestUploadResponse)
%}

### Run import on ballot manifest
POST  http://localhost:8888/import-ballot-manifest
Content-Type: application/json

{{manifestUploadResponse}}

### Log out
POST http://localhost:8888/unauthenticate
Content-Type: application/json

{
  "username":{{countyUsername}}
}

### Now county 41
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":"countyadmin41",
  "password":""
}

> {%
    client.global.set("countyUsername", "countyadmin41")
%}


### POST request for second factor.
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":{{countyUsername}},
  "second_factor":"s d f"
}

### GET the county dashboard.
GET http://localhost:8888/county-dashboard

### POST the manifest and its hash
POST http://localhost:8888/upload-file
Content-Type: multipart/form-data; boundary=TheBoundary

--TheBoundary
Content-Disposition: form-data; name="file"; filename="Byron-41-manifest.csv"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-41-manifest.csv

--TheBoundary
Content-Disposition: form-data; name="hash"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-41-manifest.csv.sha256sum
--TheBoundary--

> {%
    const manifestUploadResponse = response.body;
    client.global.set("manifestUploadResponse", manifestUploadResponse)
%}

### Run import on ballot manifest
POST  http://localhost:8888/import-ballot-manifest
Content-Type: application/json

{{manifestUploadResponse}}

### Log out
POST http://localhost:8888/unauthenticate
Content-Type: application/json

{
  "username":{{countyUsername}}
}

### Now county 42
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":"countyadmin42",
  "password":""
}

> {%
    client.global.set("countyUsername", "countyadmin42")
%}


### POST request for second factor.
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":{{countyUsername}},
  "second_factor":"s d f"
}

### GET the county dashboard.
GET http://localhost:8888/county-dashboard

### POST the manifest and its hash
POST http://localhost:8888/upload-file
Content-Type: multipart/form-data; boundary=TheBoundary

--TheBoundary
Content-Disposition: form-data; name="file"; filename="Byron-42-manifest.csv"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-42-manifest.csv

--TheBoundary
Content-Disposition: form-data; name="hash"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-42-manifest.csv.sha256sum
--TheBoundary--

> {%
    const manifestUploadResponse = response.body;
    client.global.set("manifestUploadResponse", manifestUploadResponse)
%}

### Run import on ballot manifest
POST  http://localhost:8888/import-ballot-manifest
Content-Type: application/json

{{manifestUploadResponse}}

### Log out
POST http://localhost:8888/unauthenticate
Content-Type: application/json

{
  "username":{{countyUsername}}
}

### Now county 43
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":"countyadmin43",
  "password":""
}

> {%
    client.global.set("countyUsername", "countyadmin43")
%}


### POST request for second factor.
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":{{countyUsername}},
  "second_factor":"s d f"
}

### GET the county dashboard.
GET http://localhost:8888/county-dashboard

### POST the manifest and its hash
POST http://localhost:8888/upload-file
Content-Type: multipart/form-data; boundary=TheBoundary

--TheBoundary
Content-Disposition: form-data; name="file"; filename="Byron-43-manifest.csv"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-43-manifest.csv

--TheBoundary
Content-Disposition: form-data; name="hash"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-43-manifest.csv.sha256sum
--TheBoundary--

> {%
    const manifestUploadResponse = response.body;
    client.global.set("manifestUploadResponse", manifestUploadResponse)
%}

### Run import on ballot manifest
POST  http://localhost:8888/import-ballot-manifest
Content-Type: application/json

{{manifestUploadResponse}}

### Log out
POST http://localhost:8888/unauthenticate
Content-Type: application/json

{
  "username":{{countyUsername}}
}

### Now county 44
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":"countyadmin44",
  "password":""
}

> {%
    client.global.set("countyUsername", "countyadmin44")
%}


### POST request for second factor.
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":{{countyUsername}},
  "second_factor":"s d f"
}

### GET the county dashboard.
GET http://localhost:8888/county-dashboard

### POST the manifest and its hash
POST http://localhost:8888/upload-file
Content-Type: multipart/form-data; boundary=TheBoundary

--TheBoundary
Content-Disposition: form-data; name="file"; filename="Byron-44-manifest.csv"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-44-manifest.csv

--TheBoundary
Content-Disposition: form-data; name="hash"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-44-manifest.csv.sha256sum
--TheBoundary--

> {%
    const manifestUploadResponse = response.body;
    client.global.set("manifestUploadResponse", manifestUploadResponse)
%}

### Run import on ballot manifest
POST  http://localhost:8888/import-ballot-manifest
Content-Type: application/json

{{manifestUploadResponse}}

### Log out
POST http://localhost:8888/unauthenticate
Content-Type: application/json

{
  "username":{{countyUsername}}
}

### Now county 45
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":"countyadmin45",
  "password":""
}

> {%
    client.global.set("countyUsername", "countyadmin45")
%}


### POST request for second factor.
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":{{countyUsername}},
  "second_factor":"s d f"
}

### GET the county dashboard.
GET http://localhost:8888/county-dashboard

### POST the manifest and its hash
POST http://localhost:8888/upload-file
Content-Type: multipart/form-data; boundary=TheBoundary

--TheBoundary
Content-Disposition: form-data; name="file"; filename="Byron-45-manifest.csv"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-45-manifest.csv

--TheBoundary
Content-Disposition: form-data; name="hash"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-45-manifest.csv.sha256sum
--TheBoundary--

> {%
    const manifestUploadResponse = response.body;
    client.global.set("manifestUploadResponse", manifestUploadResponse)
%}

### Run import on ballot manifest
POST  http://localhost:8888/import-ballot-manifest
Content-Type: application/json

{{manifestUploadResponse}}

### Log out
POST http://localhost:8888/unauthenticate
Content-Type: application/json

{
  "username":{{countyUsername}}
}

### Now county 46
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":"countyadmin46",
  "password":""
}

> {%
    client.global.set("countyUsername", "countyadmin46")
%}


### POST request for second factor.
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":{{countyUsername}},
  "second_factor":"s d f"
}

### GET the county dashboard.
GET http://localhost:8888/county-dashboard

### POST the manifest and its hash
POST http://localhost:8888/upload-file
Content-Type: multipart/form-data; boundary=TheBoundary

--TheBoundary
Content-Disposition: form-data; name="file"; filename="Byron-46-manifest.csv"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-46-manifest.csv

--TheBoundary
Content-Disposition: form-data; name="hash"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-46-manifest.csv.sha256sum
--TheBoundary--

> {%
    const manifestUploadResponse = response.body;
    client.global.set("manifestUploadResponse", manifestUploadResponse)
%}

### Run import on ballot manifest
POST  http://localhost:8888/import-ballot-manifest
Content-Type: application/json

{{manifestUploadResponse}}

### Log out
POST http://localhost:8888/unauthenticate
Content-Type: application/json

{
  "username":{{countyUsername}}
}

### Now county 47
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":"countyadmin47",
  "password":""
}

> {%
    client.global.set("countyUsername", "countyadmin47")
%}


### POST request for second factor.
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":{{countyUsername}},
  "second_factor":"s d f"
}

### GET the county dashboard.
GET http://localhost:8888/county-dashboard

### POST the manifest and its hash
POST http://localhost:8888/upload-file
Content-Type: multipart/form-data; boundary=TheBoundary

--TheBoundary
Content-Disposition: form-data; name="file"; filename="Byron-47-manifest.csv"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-47-manifest.csv

--TheBoundary
Content-Disposition: form-data; name="hash"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-47-manifest.csv.sha256sum
--TheBoundary--

> {%
    const manifestUploadResponse = response.body;
    client.global.set("manifestUploadResponse", manifestUploadResponse)
%}

### Run import on ballot manifest
POST  http://localhost:8888/import-ballot-manifest
Content-Type: application/json

{{manifestUploadResponse}}

### Log out
POST http://localhost:8888/unauthenticate
Content-Type: application/json

{
  "username":{{countyUsername}}
}

### Now county 48
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":"countyadmin48",
  "password":""
}

> {%
    client.global.set("countyUsername", "countyadmin48")
%}


### POST request for second factor.
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":{{countyUsername}},
  "second_factor":"s d f"
}

### GET the county dashboard.
GET http://localhost:8888/county-dashboard

### POST the manifest and its hash
POST http://localhost:8888/upload-file
Content-Type: multipart/form-data; boundary=TheBoundary

--TheBoundary
Content-Disposition: form-data; name="file"; filename="Byron-48-manifest.csv"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-48-manifest.csv

--TheBoundary
Content-Disposition: form-data; name="hash"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-48-manifest.csv.sha256sum
--TheBoundary--

> {%
    const manifestUploadResponse = response.body;
    client.global.set("manifestUploadResponse", manifestUploadResponse)
%}

### Run import on ballot manifest
POST  http://localhost:8888/import-ballot-manifest
Content-Type: application/json

{{manifestUploadResponse}}

### Log out
POST http://localhost:8888/unauthenticate
Content-Type: application/json

{
  "username":{{countyUsername}}
}

### Now county 49
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":"countyadmin49",
  "password":""
}

> {%
    client.global.set("countyUsername", "countyadmin49")
%}


### POST request for second factor.
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":{{countyUsername}},
  "second_factor":"s d f"
}

### GET the county dashboard.
GET http://localhost:8888/county-dashboard

### POST the manifest and its hash
POST http://localhost:8888/upload-file
Content-Type: multipart/form-data; boundary=TheBoundary

--TheBoundary
Content-Disposition: form-data; name="file"; filename="Byron-49-manifest.csv"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-49-manifest.csv

--TheBoundary
Content-Disposition: form-data; name="hash"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-49-manifest.csv.sha256sum
--TheBoundary--

> {%
    const manifestUploadResponse = response.body;
    client.global.set("manifestUploadResponse", manifestUploadResponse)
%}

### Run import on ballot manifest
POST  http://localhost:8888/import-ballot-manifest
Content-Type: application/json

{{manifestUploadResponse}}

### Log out
POST http://localhost:8888/unauthenticate
Content-Type: application/json

{
  "username":{{countyUsername}}
}

### Now county 50
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":"countyadmin50",
  "password":""
}

> {%
    client.global.set("countyUsername", "countyadmin50")
%}


### POST request for second factor.
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":{{countyUsername}},
  "second_factor":"s d f"
}

### GET the county dashboard.
GET http://localhost:8888/county-dashboard

### POST the manifest and its hash
POST http://localhost:8888/upload-file
Content-Type: multipart/form-data; boundary=TheBoundary

--TheBoundary
Content-Disposition: form-data; name="file"; filename="Byron-50-manifest.csv"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-50-manifest.csv

--TheBoundary
Content-Disposition: form-data; name="hash"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-50-manifest.csv.sha256sum
--TheBoundary--

> {%
    const manifestUploadResponse = response.body;
    client.global.set("manifestUploadResponse", manifestUploadResponse)
%}

### Run import on ballot manifest
POST  http://localhost:8888/import-ballot-manifest
Content-Type: application/json

{{manifestUploadResponse}}

### Log out
POST http://localhost:8888/unauthenticate
Content-Type: application/json

{
  "username":{{countyUsername}}
}

### Now county 51
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":"countyadmin51",
  "password":""
}

> {%
    client.global.set("countyUsername", "countyadmin51")
%}


### POST request for second factor.
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":{{countyUsername}},
  "second_factor":"s d f"
}

### GET the county dashboard.
GET http://localhost:8888/county-dashboard

### POST the manifest and its hash
POST http://localhost:8888/upload-file
Content-Type: multipart/form-data; boundary=TheBoundary

--TheBoundary
Content-Disposition: form-data; name="file"; filename="Byron-51-manifest.csv"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-51-manifest.csv

--TheBoundary
Content-Disposition: form-data; name="hash"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-51-manifest.csv.sha256sum
--TheBoundary--

> {%
    const manifestUploadResponse = response.body;
    client.global.set("manifestUploadResponse", manifestUploadResponse)
%}

### Run import on ballot manifest
POST  http://localhost:8888/import-ballot-manifest
Content-Type: application/json

{{manifestUploadResponse}}

### Log out
POST http://localhost:8888/unauthenticate
Content-Type: application/json

{
  "username":{{countyUsername}}
}

### Now county 52
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":"countyadmin52",
  "password":""
}

> {%
    client.global.set("countyUsername", "countyadmin52")
%}


### POST request for second factor.
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":{{countyUsername}},
  "second_factor":"s d f"
}

### GET the county dashboard.
GET http://localhost:8888/county-dashboard

### POST the manifest and its hash
POST http://localhost:8888/upload-file
Content-Type: multipart/form-data; boundary=TheBoundary

--TheBoundary
Content-Disposition: form-data; name="file"; filename="Byron-52-manifest.csv"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-52-manifest.csv

--TheBoundary
Content-Disposition: form-data; name="hash"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-52-manifest.csv.sha256sum
--TheBoundary--

> {%
    const manifestUploadResponse = response.body;
    client.global.set("manifestUploadResponse", manifestUploadResponse)
%}

### Run import on ballot manifest
POST  http://localhost:8888/import-ballot-manifest
Content-Type: application/json

{{manifestUploadResponse}}

### Log out
POST http://localhost:8888/unauthenticate
Content-Type: application/json

{
  "username":{{countyUsername}}
}

### Now county 53
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":"countyadmin53",
  "password":""
}

> {%
    client.global.set("countyUsername", "countyadmin53")
%}


### POST request for second factor.
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":{{countyUsername}},
  "second_factor":"s d f"
}

### GET the county dashboard.
GET http://localhost:8888/county-dashboard

### POST the manifest and its hash
POST http://localhost:8888/upload-file
Content-Type: multipart/form-data; boundary=TheBoundary

--TheBoundary
Content-Disposition: form-data; name="file"; filename="Byron-53-manifest.csv"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-53-manifest.csv

--TheBoundary
Content-Disposition: form-data; name="hash"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-53-manifest.csv.sha256sum
--TheBoundary--

> {%
    const manifestUploadResponse = response.body;
    client.global.set("manifestUploadResponse", manifestUploadResponse)
%}

### Run import on ballot manifest
POST  http://localhost:8888/import-ballot-manifest
Content-Type: application/json

{{manifestUploadResponse}}

### Log out
POST http://localhost:8888/unauthenticate
Content-Type: application/json

{
  "username":{{countyUsername}}
}

### Now county 54
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":"countyadmin54",
  "password":""
}

> {%
    client.global.set("countyUsername", "countyadmin54")
%}


### POST request for second factor.
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":{{countyUsername}},
  "second_factor":"s d f"
}

### GET the county dashboard.
GET http://localhost:8888/county-dashboard

### POST the manifest and its hash
POST http://localhost:8888/upload-file
Content-Type: multipart/form-data; boundary=TheBoundary

--TheBoundary
Content-Disposition: form-data; name="file"; filename="Byron-54-manifest.csv"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-54-manifest.csv

--TheBoundary
Content-Disposition: form-data; name="hash"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-54-manifest.csv.sha256sum
--TheBoundary--

> {%
    const manifestUploadResponse = response.body;
    client.global.set("manifestUploadResponse", manifestUploadResponse)
%}

### Run import on ballot manifest
POST  http://localhost:8888/import-ballot-manifest
Content-Type: application/json

{{manifestUploadResponse}}

### Log out
POST http://localhost:8888/unauthenticate
Content-Type: application/json

{
  "username":{{countyUsername}}
}

### Now county 55
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":"countyadmin55",
  "password":""
}

> {%
    client.global.set("countyUsername", "countyadmin55")
%}


### POST request for second factor.
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":{{countyUsername}},
  "second_factor":"s d f"
}

### GET the county dashboard.
GET http://localhost:8888/county-dashboard

### POST the manifest and its hash
POST http://localhost:8888/upload-file
Content-Type: multipart/form-data; boundary=TheBoundary

--TheBoundary
Content-Disposition: form-data; name="file"; filename="Byron-55-manifest.csv"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-55-manifest.csv

--TheBoundary
Content-Disposition: form-data; name="hash"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-55-manifest.csv.sha256sum
--TheBoundary--

> {%
    const manifestUploadResponse = response.body;
    client.global.set("manifestUploadResponse", manifestUploadResponse)
%}

### Run import on ballot manifest
POST  http://localhost:8888/import-ballot-manifest
Content-Type: application/json

{{manifestUploadResponse}}

### Log out
POST http://localhost:8888/unauthenticate
Content-Type: application/json

{
  "username":{{countyUsername}}
}

### Now county 56
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":"countyadmin56",
  "password":""
}

> {%
    client.global.set("countyUsername", "countyadmin56")
%}


### POST request for second factor.
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":{{countyUsername}},
  "second_factor":"s d f"
}

### GET the county dashboard.
GET http://localhost:8888/county-dashboard

### POST the manifest and its hash
POST http://localhost:8888/upload-file
Content-Type: multipart/form-data; boundary=TheBoundary

--TheBoundary
Content-Disposition: form-data; name="file"; filename="Byron-56-manifest.csv"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-56-manifest.csv

--TheBoundary
Content-Disposition: form-data; name="hash"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-56-manifest.csv.sha256sum
--TheBoundary--

> {%
    const manifestUploadResponse = response.body;
    client.global.set("manifestUploadResponse", manifestUploadResponse)
%}

### Run import on ballot manifest
POST  http://localhost:8888/import-ballot-manifest
Content-Type: application/json

{{manifestUploadResponse}}

### Log out
POST http://localhost:8888/unauthenticate
Content-Type: application/json

{
  "username":{{countyUsername}}
}

### Now county 57
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":"countyadmin57",
  "password":""
}

> {%
    client.global.set("countyUsername", "countyadmin57")
%}


### POST request for second factor.
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":{{countyUsername}},
  "second_factor":"s d f"
}

### GET the county dashboard.
GET http://localhost:8888/county-dashboard

### POST the manifest and its hash
POST http://localhost:8888/upload-file
Content-Type: multipart/form-data; boundary=TheBoundary

--TheBoundary
Content-Disposition: form-data; name="file"; filename="Byron-57-manifest.csv"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-57-manifest.csv

--TheBoundary
Content-Disposition: form-data; name="hash"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-57-manifest.csv.sha256sum
--TheBoundary--

> {%
    const manifestUploadResponse = response.body;
    client.global.set("manifestUploadResponse", manifestUploadResponse)
%}

### Run import on ballot manifest
POST  http://localhost:8888/import-ballot-manifest
Content-Type: application/json

{{manifestUploadResponse}}

### Log out
POST http://localhost:8888/unauthenticate
Content-Type: application/json

{
  "username":{{countyUsername}}
}

### Now county 58
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":"countyadmin58",
  "password":""
}

> {%
    client.global.set("countyUsername", "countyadmin58")
%}


### POST request for second factor.
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":{{countyUsername}},
  "second_factor":"s d f"
}

### GET the county dashboard.
GET http://localhost:8888/county-dashboard

### POST the manifest and its hash
POST http://localhost:8888/upload-file
Content-Type: multipart/form-data; boundary=TheBoundary

--TheBoundary
Content-Disposition: form-data; name="file"; filename="Byron-58-manifest.csv"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-58-manifest.csv

--TheBoundary
Content-Disposition: form-data; name="hash"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-58-manifest.csv.sha256sum
--TheBoundary--

> {%
    const manifestUploadResponse = response.body;
    client.global.set("manifestUploadResponse", manifestUploadResponse)
%}

### Run import on ballot manifest
POST  http://localhost:8888/import-ballot-manifest
Content-Type: application/json

{{manifestUploadResponse}}

### Log out
POST http://localhost:8888/unauthenticate
Content-Type: application/json

{
  "username":{{countyUsername}}
}

### Now county 59
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":"countyadmin59",
  "password":""
}

> {%
    client.global.set("countyUsername", "countyadmin59")
%}


### POST request for second factor.
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":{{countyUsername}},
  "second_factor":"s d f"
}

### GET the county dashboard.
GET http://localhost:8888/county-dashboard

### POST the manifest and its hash
POST http://localhost:8888/upload-file
Content-Type: multipart/form-data; boundary=TheBoundary

--TheBoundary
Content-Disposition: form-data; name="file"; filename="Byron-59-manifest.csv"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-59-manifest.csv

--TheBoundary
Content-Disposition: form-data; name="hash"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-59-manifest.csv.sha256sum
--TheBoundary--

> {%
    const manifestUploadResponse = response.body;
    client.global.set("manifestUploadResponse", manifestUploadResponse)
%}

### Run import on ballot manifest
POST  http://localhost:8888/import-ballot-manifest
Content-Type: application/json

{{manifestUploadResponse}}

### Log out
POST http://localhost:8888/unauthenticate
Content-Type: application/json

{
  "username":{{countyUsername}}
}

### Now county 60
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":"countyadmin60",
  "password":""
}

> {%
    client.global.set("countyUsername", "countyadmin60")
%}


### POST request for second factor.
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":{{countyUsername}},
  "second_factor":"s d f"
}

### GET the county dashboard.
GET http://localhost:8888/county-dashboard

### POST the manifest and its hash
POST http://localhost:8888/upload-file
Content-Type: multipart/form-data; boundary=TheBoundary

--TheBoundary
Content-Disposition: form-data; name="file"; filename="Byron-60-manifest.csv"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-60-manifest.csv

--TheBoundary
Content-Disposition: form-data; name="hash"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-60-manifest.csv.sha256sum
--TheBoundary--

> {%
    const manifestUploadResponse = response.body;
    client.global.set("manifestUploadResponse", manifestUploadResponse)
%}

### Run import on ballot manifest
POST  http://localhost:8888/import-ballot-manifest
Content-Type: application/json

{{manifestUploadResponse}}

### Log out
POST http://localhost:8888/unauthenticate
Content-Type: application/json

{
  "username":{{countyUsername}}
}

### Now county 61
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":"countyadmin61",
  "password":""
}

> {%
    client.global.set("countyUsername", "countyadmin61")
%}


### POST request for second factor.
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":{{countyUsername}},
  "second_factor":"s d f"
}

### GET the county dashboard.
GET http://localhost:8888/county-dashboard

### POST the manifest and its hash
POST http://localhost:8888/upload-file
Content-Type: multipart/form-data; boundary=TheBoundary

--TheBoundary
Content-Disposition: form-data; name="file"; filename="Byron-61-manifest.csv"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-61-manifest.csv

--TheBoundary
Content-Disposition: form-data; name="hash"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-61-manifest.csv.sha256sum
--TheBoundary--

> {%
    const manifestUploadResponse = response.body;
    client.global.set("manifestUploadResponse", manifestUploadResponse)
%}

### Run import on ballot manifest
POST  http://localhost:8888/import-ballot-manifest
Content-Type: application/json

{{manifestUploadResponse}}

### Log out
POST http://localhost:8888/unauthenticate
Content-Type: application/json

{
  "username":{{countyUsername}}
}

### Now county 62
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":"countyadmin62",
  "password":""
}

> {%
    client.global.set("countyUsername", "countyadmin62")
%}


### POST request for second factor.
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":{{countyUsername}},
  "second_factor":"s d f"
}

### GET the county dashboard.
GET http://localhost:8888/county-dashboard

### POST the manifest and its hash
POST http://localhost:8888/upload-file
Content-Type: multipart/form-data; boundary=TheBoundary

--TheBoundary
Content-Disposition: form-data; name="file"; filename="Byron-62-manifest.csv"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-62-manifest.csv

--TheBoundary
Content-Disposition: form-data; name="hash"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-62-manifest.csv.sha256sum
--TheBoundary--

> {%
    const manifestUploadResponse = response.body;
    client.global.set("manifestUploadResponse", manifestUploadResponse)
%}

### Run import on ballot manifest
POST  http://localhost:8888/import-ballot-manifest
Content-Type: application/json

{{manifestUploadResponse}}

### Log out
POST http://localhost:8888/unauthenticate
Content-Type: application/json

{
  "username":{{countyUsername}}
}

### Now county 63
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":"countyadmin63",
  "password":""
}

> {%
    client.global.set("countyUsername", "countyadmin63")
%}


### POST request for second factor.
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":{{countyUsername}},
  "second_factor":"s d f"
}

### GET the county dashboard.
GET http://localhost:8888/county-dashboard

### POST the manifest and its hash
POST http://localhost:8888/upload-file
Content-Type: multipart/form-data; boundary=TheBoundary

--TheBoundary
Content-Disposition: form-data; name="file"; filename="Byron-63-manifest.csv"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-63-manifest.csv

--TheBoundary
Content-Disposition: form-data; name="hash"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-63-manifest.csv.sha256sum
--TheBoundary--

> {%
    const manifestUploadResponse = response.body;
    client.global.set("manifestUploadResponse", manifestUploadResponse)
%}

### Run import on ballot manifest
POST  http://localhost:8888/import-ballot-manifest
Content-Type: application/json

{{manifestUploadResponse}}

### Log out
POST http://localhost:8888/unauthenticate
Content-Type: application/json

{
  "username":{{countyUsername}}
}

### Now county 64
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":"countyadmin64",
  "password":""
}

> {%
    client.global.set("countyUsername", "countyadmin64")
%}


### POST request for second factor.
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":{{countyUsername}},
  "second_factor":"s d f"
}

### GET the county dashboard.
GET http://localhost:8888/county-dashboard

### POST the manifest and its hash
POST http://localhost:8888/upload-file
Content-Type: multipart/form-data; boundary=TheBoundary

--TheBoundary
Content-Disposition: form-data; name="file"; filename="Byron-64-manifest.csv"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-64-manifest.csv

--TheBoundary
Content-Disposition: form-data; name="hash"
Content-Type: text/csv

< ../resources/CSVs/split-Byron/Byron-64-manifest.csv.sha256sum
--TheBoundary--

> {%
    const manifestUploadResponse = response.body;
    client.global.set("manifestUploadResponse", manifestUploadResponse)
%}

### Run import on ballot manifest
POST  http://localhost:8888/import-ballot-manifest
Content-Type: application/json

{{manifestUploadResponse}}

### Log out
POST http://localhost:8888/unauthenticate
Content-Type: application/json

{
  "username":{{countyUsername}}
}

