### This loads all the CVRs for Demo1 - see README for details.

### 1. Adams County
### POST request with basic login.
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":"countyadmin1",
  "password":""
}

### POST request for second factor.
POST http://localhost:8888/auth-admin
Content-Type: application/json

{
  "username":"countyadmin1",
  "second_factor":"s d f"
}

### GET the county dashboard.
GET http://localhost:8888/county-dashboard

### POST the cvr file and its hash
POST http://localhost:8888/upload-file
Content-Type: multipart/form-data; boundary=TheBoundary

--TheBoundary
Content-Disposition: form-data; name="file"; filename="1-adams-cvrexport-plusByron-1.csv"
Content-Type: text/csv

< ../resources/CSVs/Demo1/1-adams-cvrexport-plusByron-1.csv

--TheBoundary
Content-Disposition: form-data; name="hash"
Content-Type: text/csv

225578912f620a42740b3efe076e679bb3ee3e08ce70c6982eaf19d033d819be

> {%
    const idLine = response.body.split(",")[4];
    const idOnly = idLine.replace("\"id\":","");
    console.log("Extracting ID only:"+idOnly);
    client.global.set("cvrID", idOnly);
%}

### < ../resources/CSVs/Demo1/1-adams-cvrexport-plusByron-1.csv.sha256sum
### Request the CVR export to be imported
### TODO The ID must match the ID in the database, which gets returned in the upload to response.
### Timestamp doesn't seem to matter.
POST http://localhost:8888/import-cvr-export
Content-Type: application/json

{
  "approximateRecordCount": 288,
  "countyId": 1,
  "fileName": "1-adams-cvrexport-plusByron-1.csv",
  "hash": "225578912F620A42740B3EFE076E679BB3EE3E08CE70C6982EAF19D033D819BE",
  "id": {{cvrID}},
  "result": {"success": false},
  "status": "HASH_VERIFIED",
  "size": 64925,
  "timestamp": "2024-09-07T00:24:52.892324812Z"
}

### POST the manifest and its hash
POST http://localhost:8888/upload-file
Content-Type: multipart/form-data; boundary=TheBoundary

--TheBoundary
Content-Disposition: form-data; name="file"; filename="1-adams-plusByron-1-manifest.csv"
Content-Type: text/csv

< ../resources/CSVs/Demo1/1-adams-plusByron-1-manifest.csv

--TheBoundary
Content-Disposition: form-data; name="hash"
Content-Type: text/csv

< ../resources/CSVs/Demo1/1-adams-plusByron-1-manifest.csv.sha256sum

> {%
    client.global.set("postData", JSON.stringify(response.body));
%}

### Run import on ballot manifest
POST  http://localhost:8888/import-ballot-manifest
Content-Type: application/json

{
"postData" : {
"mimeType": "text/plain;charset=UTF-8",
"params": [],
"text": {
"approximateRecordCount": 2,
    "countyId": 1,
    "fileName": "ThreeCandidatesTenVotes_Manifest.csv",
    "hash": "5D602A0A0B2BC51A2E9F1F6EFD8650FDD748E4FDD8268104A43A633588A998C3",
    "id": 160612,
    "result": {"success": false},
    "status": "HASH_VERIFIED",
    "size": 78,
    "timestamp": "2024-09-07T00:24:52.892324812Z"
}
}
}


### From the file upload response:
### "text": "{\n  \"approximateRecordCount\": 2,\n  \"countyId\": 1,\n  \"fileName\": \"ThreeCandidatesTenVotes_Manifest.csv\",\n  \"hash\": \"5D602A0A0B2BC51A2E9F1F6EFD8650FDD748E4FDD8268104A43A633588A998C3\",\n  \"id\": 160612,\n  \"result\": {\n    \"success\": false\n  },\n  \"status\": \"HASH_VERIFIED\",\n  \"size\": 78,\n  \"timestamp\": \"2024-09-07T00:24:52.892324812Z\"\n}"
### Sent back in the import-ballot-manifest:
### "text": "{\"approximateRecordCount\":2,\"countyId\":1,\"fileName\":\"ThreeCandidatesTenVotes_Manifest.csv\",\"hash\":\"5D602A0A0B2BC51A2E9F1F6EFD8650FDD748E4FDD8268104A43A633588A998C3\",\"id\":160612,\"result\":{\"success\":false},\"status\":\"HASH_VERIFIED\",\"size\":78,\"timestamp\":\"2024-09-07T00:24:52.892324812Z\"}
### which is identical.


###> {%
###    const testData = "This is a test";
###    request.variables.set("postData", testData);
### %}


