INSERT INTO public.assertion (assertion_type, id, contest_name, current_risk, difficulty, diluted_margin, estimated_samples_to_audit, loser, margin, one_vote_over_count, one_vote_under_count, optimistic_samples_to_audit, other_count, two_vote_over_count, two_vote_under_count, version, winner) VALUES ('NEB', 23, 'City of Boulder Mayoral Candidates', 1.00000000, 46.40923196276183, 0.02154744, 339, 'Nicole Speer', 2578, 0, 0, 339, 0, 0, 0, 1, 'Aaron Brockett');
INSERT INTO public.assertion (assertion_type, id, contest_name, current_risk, difficulty, diluted_margin, estimated_samples_to_audit, loser, margin, one_vote_over_count, one_vote_under_count, optimistic_samples_to_audit, other_count, two_vote_over_count, two_vote_under_count, version, winner) VALUES ('NEB', 24, 'City of Boulder Mayoral Candidates', 1.00000000, 14.260190703218116, 0.07012529, 104, 'Paul Tweedlie', 8390, 0, 0, 104, 0, 0, 0, 1, 'Aaron Brockett');
INSERT INTO public.assertion (assertion_type, id, contest_name, current_risk, difficulty, diluted_margin, estimated_samples_to_audit, loser, margin, one_vote_over_count, one_vote_under_count, optimistic_samples_to_audit, other_count, two_vote_over_count, two_vote_under_count, version, winner) VALUES ('NEN', 25, 'City of Boulder Mayoral Candidates', 1.00000000, 97.42915309446254, 0.01026387, 710, 'Bob Yates', 1228, 0, 0, 710, 0, 0, 0, 1, 'Aaron Brockett');
INSERT INTO public.assertion (assertion_type, id, contest_name, current_risk, difficulty, diluted_margin, estimated_samples_to_audit, loser, margin, one_vote_over_count, one_vote_under_count, optimistic_samples_to_audit, other_count, two_vote_over_count, two_vote_under_count, version, winner) VALUES ('NEN', 1, 'Uralla Mayoral', 1.00000000, 1.5727953410981697, 0.63581063, 12, 'LEDGER Natasha', 2404, 0, 0, 12, 0, 0, 0, 14, 'BELL Robert');
INSERT INTO public.assertion (assertion_type, id, contest_name, current_risk, difficulty, diluted_margin, estimated_samples_to_audit, loser, margin, one_vote_over_count, one_vote_under_count, optimistic_samples_to_audit, other_count, two_vote_over_count, two_vote_under_count, version, winner) VALUES ('NEN', 2, 'Uralla Mayoral', 1.00000000, 1.6297413793103448, 0.61359429, 12, 'STRUTT Isabel', 2320, 0, 0, 12, 0, 0, 0, 14, 'BELL Robert');
INSERT INTO public.assertion (assertion_type, id, contest_name, current_risk, difficulty, diluted_margin, estimated_samples_to_audit, loser, margin, one_vote_over_count, one_vote_under_count, optimistic_samples_to_audit, other_count, two_vote_over_count, two_vote_under_count, version, winner) VALUES ('NEN', 3, 'Uralla Mayoral', 1.00000000, 1.6034775233248515, 0.62364454, 12, 'LEDGER Natasha', 2358, 0, 0, 12, 0, 0, 0, 14, 'BELL Robert');
INSERT INTO public.assertion (assertion_type, id, contest_name, current_risk, difficulty, diluted_margin, estimated_samples_to_audit, loser, margin, one_vote_over_count, one_vote_under_count, optimistic_samples_to_audit, other_count, two_vote_over_count, two_vote_under_count, version, winner) VALUES ('NEN', 11, 'Byron Mayoral', 1.00000000, 133.03867924528302, 0.00751661, 861, 'SWIVEL Mark', 1060, 0, 0, 861, 0, 0, 0, 505, 'LYON Michael');
INSERT INTO public.assertion (assertion_type, id, contest_name, current_risk, difficulty, diluted_margin, estimated_samples_to_audit, loser, margin, one_vote_over_count, one_vote_under_count, optimistic_samples_to_audit, other_count, two_vote_over_count, two_vote_under_count, version, winner) VALUES ('NEN', 8, 'Byron Mayoral', 1.00000000, 61.26020851433536, 0.01632381, 481, 'COOREY Cate', 2302, 0, 0, 480, 0, 0, 0, 342, 'LYON Michael');
INSERT INTO public.assertion (assertion_type, id, contest_name, current_risk, difficulty, diluted_margin, estimated_samples_to_audit, loser, margin, one_vote_over_count, one_vote_under_count, optimistic_samples_to_audit, other_count, two_vote_over_count, two_vote_under_count, version, winner) VALUES ('NEB', 4, 'Byron Mayoral', 1.00000000, 67.21687321258341, 0.01487722, 528, 'HUNTER Alan', 2098, 0, 0, 527, 0, 0, 0, 362, 'LYON Michael');
INSERT INTO public.assertion (assertion_type, id, contest_name, current_risk, difficulty, diluted_margin, estimated_samples_to_audit, loser, margin, one_vote_over_count, one_vote_under_count, optimistic_samples_to_audit, other_count, two_vote_over_count, two_vote_under_count, version, winner) VALUES ('NEB', 5, 'Byron Mayoral', 1.00000000, 75.57395498392283, 0.01323207, 594, 'CLARKE Bruce', 1866, 0, 0, 593, 0, 0, 0, 388, 'LYON Michael');
INSERT INTO public.assertion (assertion_type, id, contest_name, current_risk, difficulty, diluted_margin, estimated_samples_to_audit, loser, margin, one_vote_over_count, one_vote_under_count, optimistic_samples_to_audit, other_count, two_vote_over_count, two_vote_under_count, version, winner) VALUES ('NEB', 6, 'Byron Mayoral', 1.00000000, 50.22115384615385, 0.01991193, 395, 'ANDERSON John', 2808, 0, 0, 394, 0, 0, 0, 303, 'LYON Michael');
INSERT INTO public.assertion (assertion_type, id, contest_name, current_risk, difficulty, diluted_margin, estimated_samples_to_audit, loser, margin, one_vote_over_count, one_vote_under_count, optimistic_samples_to_audit, other_count, two_vote_over_count, two_vote_under_count, version, winner) VALUES ('NEB', 7, 'Byron Mayoral', 1.00000000, 42.158744394618836, 0.02371987, 332, 'MCILRATH Christopher', 3345, 0, 0, 331, 0, 0, 0, 270, 'LYON Michael');
INSERT INTO public.assertion (assertion_type, id, contest_name, current_risk, difficulty, diluted_margin, estimated_samples_to_audit, loser, margin, one_vote_over_count, one_vote_under_count, optimistic_samples_to_audit, other_count, two_vote_over_count, two_vote_under_count, version, winner) VALUES ('NEN', 9, 'Byron Mayoral', 1.00000000, 48.39430336307481, 0.02066359, 352, 'DEY Duncan', 2914, 0, 0, 351, 0, 0, 1, 268, 'LYON Michael');
INSERT INTO public.assertion (assertion_type, id, contest_name, current_risk, difficulty, diluted_margin, estimated_samples_to_audit, loser, margin, one_vote_over_count, one_vote_under_count, optimistic_samples_to_audit, other_count, two_vote_over_count, two_vote_under_count, version, winner) VALUES ('NEN', 10, 'Byron Mayoral', 1.00000000, 61.742994746059544, 0.01619617, 485, 'PUGH Asren', 2284, 0, 0, 484, 0, 0, 0, 345, 'LYON Michael');
INSERT INTO public.assertion (assertion_type, id, contest_name, current_risk, difficulty, diluted_margin, estimated_samples_to_audit, loser, margin, one_vote_over_count, one_vote_under_count, optimistic_samples_to_audit, other_count, two_vote_over_count, two_vote_under_count, version, winner) VALUES ('NEN', 12, 'Byron Mayoral', 1.00000000, 114.18704453441296, 0.00875756, 896, 'COOREY Cate', 1235, 0, 0, 895, 0, 0, 0, 478, 'LYON Michael');
INSERT INTO public.assertion (assertion_type, id, contest_name, current_risk, difficulty, diluted_margin, estimated_samples_to_audit, loser, margin, one_vote_over_count, one_vote_under_count, optimistic_samples_to_audit, other_count, two_vote_over_count, two_vote_under_count, version, winner) VALUES ('NEN', 13, 'Byron Mayoral', 1.00000000, 42.87655822438431, 0.02332277, 312, 'DEY Duncan', 3289, 0, 0, 311, 0, 0, 1, 249, 'LYON Michael');
INSERT INTO public.assertion (assertion_type, id, contest_name, current_risk, difficulty, diluted_margin, estimated_samples_to_audit, loser, margin, one_vote_over_count, one_vote_under_count, optimistic_samples_to_audit, other_count, two_vote_over_count, two_vote_under_count, version, winner) VALUES ('NEN', 14, 'Byron Mayoral', 1.00000000, 96.6559287183002, 0.01034598, 702, 'DEY Duncan', 1459, 0, 0, 701, 0, 0, 1, 387, 'LYON Michael');
INSERT INTO public.assertion (assertion_type, id, contest_name, current_risk, difficulty, diluted_margin, estimated_samples_to_audit, loser, margin, one_vote_over_count, one_vote_under_count, optimistic_samples_to_audit, other_count, two_vote_over_count, two_vote_under_count, version, winner) VALUES ('NEN', 15, 'Byron Mayoral', 1.00000000, 78.21464226289517, 0.01278533, 614, 'PUGH Asren', 1803, 0, 0, 613, 0, 0, 0, 395, 'LYON Michael');
INSERT INTO public.assertion (assertion_type, id, contest_name, current_risk, difficulty, diluted_margin, estimated_samples_to_audit, loser, margin, one_vote_over_count, one_vote_under_count, optimistic_samples_to_audit, other_count, two_vote_over_count, two_vote_under_count, version, winner) VALUES ('NEN', 16, 'Byron Mayoral', 1.00000000, 60.00893617021276, 0.01666418, 472, 'PUGH Asren', 2350, 0, 0, 471, 0, 0, 0, 338, 'LYON Michael');
INSERT INTO public.assertion (assertion_type, id, contest_name, current_risk, difficulty, diluted_margin, estimated_samples_to_audit, loser, margin, one_vote_over_count, one_vote_under_count, optimistic_samples_to_audit, other_count, two_vote_over_count, two_vote_under_count, version, winner) VALUES ('NEN', 17, 'Byron Mayoral', 1.00000000, 47.08547579298831, 0.02123797, 370, 'PUGH Asren', 2995, 0, 0, 369, 0, 0, 0, 290, 'LYON Michael');
INSERT INTO public.assertion (assertion_type, id, contest_name, current_risk, difficulty, diluted_margin, estimated_samples_to_audit, loser, margin, one_vote_over_count, one_vote_under_count, optimistic_samples_to_audit, other_count, two_vote_over_count, two_vote_under_count, version, winner) VALUES ('NEN', 18, 'Byron Mayoral', 1.00000000, 69.22974963181149, 0.01444466, 544, 'COOREY Cate', 2037, 0, 0, 543, 0, 0, 0, 369, 'LYON Michael');
INSERT INTO public.assertion (assertion_type, id, contest_name, current_risk, difficulty, diluted_margin, estimated_samples_to_audit, loser, margin, one_vote_over_count, one_vote_under_count, optimistic_samples_to_audit, other_count, two_vote_over_count, two_vote_under_count, version, winner) VALUES ('NEN', 19, 'Byron Mayoral', 1.00000000, 61.87845546292233, 0.01616071, 450, 'DEY Duncan', 2279, 0, 0, 449, 0, 0, 1, 309, 'LYON Michael');
INSERT INTO public.assertion (assertion_type, id, contest_name, current_risk, difficulty, diluted_margin, estimated_samples_to_audit, loser, margin, one_vote_over_count, one_vote_under_count, optimistic_samples_to_audit, other_count, two_vote_over_count, two_vote_under_count, version, winner) VALUES ('NEN', 20, 'Byron Mayoral', 1.00000000, 56.909200968523, 0.01757185, 447, 'PUGH Asren', 2478, 0, 0, 446, 0, 0, 0, 328, 'LYON Michael');
INSERT INTO public.assertion (assertion_type, id, contest_name, current_risk, difficulty, diluted_margin, estimated_samples_to_audit, loser, margin, one_vote_over_count, one_vote_under_count, optimistic_samples_to_audit, other_count, two_vote_over_count, two_vote_under_count, version, winner) VALUES ('NEN', 21, 'Byron Mayoral', 1.00000000, 48.080804636890555, 0.02079832, 378, 'PUGH Asren', 2933, 0, 0, 377, 0, 0, 0, 295, 'LYON Michael');
INSERT INTO public.assertion (assertion_type, id, contest_name, current_risk, difficulty, diluted_margin, estimated_samples_to_audit, loser, margin, one_vote_over_count, one_vote_under_count, optimistic_samples_to_audit, other_count, two_vote_over_count, two_vote_under_count, version, winner) VALUES ('NEN', 22, 'Byron Mayoral', 1.00000000, 52.995490417136416, 0.01886953, 417, 'PUGH Asren', 2661, 0, 0, 416, 0, 0, 0, 314, 'LYON Michael');


INSERT INTO public.assertion_assumed_continuing (id, assumed_continuing) VALUES (1, 'BELL Robert');
INSERT INTO public.assertion_assumed_continuing (id, assumed_continuing) VALUES (1, 'LEDGER Natasha');
INSERT INTO public.assertion_assumed_continuing (id, assumed_continuing) VALUES (2, 'BELL Robert');
INSERT INTO public.assertion_assumed_continuing (id, assumed_continuing) VALUES (2, 'STRUTT Isabel');
INSERT INTO public.assertion_assumed_continuing (id, assumed_continuing) VALUES (3, 'BELL Robert');
INSERT INTO public.assertion_assumed_continuing (id, assumed_continuing) VALUES (3, 'LEDGER Natasha');
INSERT INTO public.assertion_assumed_continuing (id, assumed_continuing) VALUES (3, 'STRUTT Isabel');
INSERT INTO public.assertion_assumed_continuing (id, assumed_continuing) VALUES (8, 'COOREY Cate');
INSERT INTO public.assertion_assumed_continuing (id, assumed_continuing) VALUES (8, 'LYON Michael');
INSERT INTO public.assertion_assumed_continuing (id, assumed_continuing) VALUES (9, 'LYON Michael');
INSERT INTO public.assertion_assumed_continuing (id, assumed_continuing) VALUES (9, 'DEY Duncan');
INSERT INTO public.assertion_assumed_continuing (id, assumed_continuing) VALUES (10, 'LYON Michael');
INSERT INTO public.assertion_assumed_continuing (id, assumed_continuing) VALUES (10, 'PUGH Asren');
INSERT INTO public.assertion_assumed_continuing (id, assumed_continuing) VALUES (11, 'LYON Michael');
INSERT INTO public.assertion_assumed_continuing (id, assumed_continuing) VALUES (11, 'SWIVEL Mark');
INSERT INTO public.assertion_assumed_continuing (id, assumed_continuing) VALUES (12, 'COOREY Cate');
INSERT INTO public.assertion_assumed_continuing (id, assumed_continuing) VALUES (12, 'LYON Michael');
INSERT INTO public.assertion_assumed_continuing (id, assumed_continuing) VALUES (12, 'SWIVEL Mark');
INSERT INTO public.assertion_assumed_continuing (id, assumed_continuing) VALUES (13, 'COOREY Cate');
INSERT INTO public.assertion_assumed_continuing (id, assumed_continuing) VALUES (13, 'LYON Michael');
INSERT INTO public.assertion_assumed_continuing (id, assumed_continuing) VALUES (13, 'DEY Duncan');
INSERT INTO public.assertion_assumed_continuing (id, assumed_continuing) VALUES (14, 'LYON Michael');
INSERT INTO public.assertion_assumed_continuing (id, assumed_continuing) VALUES (14, 'DEY Duncan');
INSERT INTO public.assertion_assumed_continuing (id, assumed_continuing) VALUES (14, 'SWIVEL Mark');
INSERT INTO public.assertion_assumed_continuing (id, assumed_continuing) VALUES (15, 'COOREY Cate');
INSERT INTO public.assertion_assumed_continuing (id, assumed_continuing) VALUES (15, 'LYON Michael');
INSERT INTO public.assertion_assumed_continuing (id, assumed_continuing) VALUES (15, 'PUGH Asren');
INSERT INTO public.assertion_assumed_continuing (id, assumed_continuing) VALUES (16, 'LYON Michael');
INSERT INTO public.assertion_assumed_continuing (id, assumed_continuing) VALUES (16, 'DEY Duncan');
INSERT INTO public.assertion_assumed_continuing (id, assumed_continuing) VALUES (16, 'PUGH Asren');
INSERT INTO public.assertion_assumed_continuing (id, assumed_continuing) VALUES (17, 'LYON Michael');
INSERT INTO public.assertion_assumed_continuing (id, assumed_continuing) VALUES (17, 'PUGH Asren');
INSERT INTO public.assertion_assumed_continuing (id, assumed_continuing) VALUES (17, 'SWIVEL Mark');
INSERT INTO public.assertion_assumed_continuing (id, assumed_continuing) VALUES (18, 'COOREY Cate');
INSERT INTO public.assertion_assumed_continuing (id, assumed_continuing) VALUES (18, 'LYON Michael');
INSERT INTO public.assertion_assumed_continuing (id, assumed_continuing) VALUES (18, 'DEY Duncan');
INSERT INTO public.assertion_assumed_continuing (id, assumed_continuing) VALUES (18, 'SWIVEL Mark');
INSERT INTO public.assertion_assumed_continuing (id, assumed_continuing) VALUES (19, 'COOREY Cate');
INSERT INTO public.assertion_assumed_continuing (id, assumed_continuing) VALUES (19, 'LYON Michael');
INSERT INTO public.assertion_assumed_continuing (id, assumed_continuing) VALUES (19, 'DEY Duncan');
INSERT INTO public.assertion_assumed_continuing (id, assumed_continuing) VALUES (19, 'PUGH Asren');
INSERT INTO public.assertion_assumed_continuing (id, assumed_continuing) VALUES (20, 'COOREY Cate');
INSERT INTO public.assertion_assumed_continuing (id, assumed_continuing) VALUES (20, 'LYON Michael');
INSERT INTO public.assertion_assumed_continuing (id, assumed_continuing) VALUES (20, 'PUGH Asren');
INSERT INTO public.assertion_assumed_continuing (id, assumed_continuing) VALUES (20, 'SWIVEL Mark');
INSERT INTO public.assertion_assumed_continuing (id, assumed_continuing) VALUES (21, 'LYON Michael');
INSERT INTO public.assertion_assumed_continuing (id, assumed_continuing) VALUES (21, 'DEY Duncan');
INSERT INTO public.assertion_assumed_continuing (id, assumed_continuing) VALUES (21, 'PUGH Asren');
INSERT INTO public.assertion_assumed_continuing (id, assumed_continuing) VALUES (21, 'SWIVEL Mark');
INSERT INTO public.assertion_assumed_continuing (id, assumed_continuing) VALUES (22, 'COOREY Cate');
INSERT INTO public.assertion_assumed_continuing (id, assumed_continuing) VALUES (22, 'LYON Michael');
INSERT INTO public.assertion_assumed_continuing (id, assumed_continuing) VALUES (22, 'DEY Duncan');
INSERT INTO public.assertion_assumed_continuing (id, assumed_continuing) VALUES (22, 'PUGH Asren');
INSERT INTO public.assertion_assumed_continuing (id, assumed_continuing) VALUES (22, 'SWIVEL Mark');
INSERT INTO public.assertion_assumed_continuing (id, assumed_continuing) VALUES (25, 'Aaron Brockett');
INSERT INTO public.assertion_assumed_continuing (id, assumed_continuing) VALUES (25, 'Bob Yates');

INSERT INTO public.generate_assertions_summary (id, contest_name, error, message, version, warning, winner) VALUES (1, 'Tied_IRV', 'TIED_WINNERS', 'Tied winners: Alice, Chuan.', 0, '', '');
INSERT INTO public.generate_assertions_summary (id, contest_name, error, message, version, warning, winner) VALUES (2, 'Uralla Mayoral', '', '', 0, '', 'BELL Robert');
INSERT INTO public.generate_assertions_summary (id, contest_name, error, message, version, warning, winner) VALUES (3, 'Byron Mayoral', '', '', 0, '', 'LYON Michael');
INSERT INTO public.generate_assertions_summary (id, contest_name, error, message, version, warning, winner) VALUES (4, 'City of Boulder Mayoral Candidates', '', '', 0, '', 'Aaron Brockett');



