INSERT INTO public.assertion (assertion_type, id, contest_name, current_risk, difficulty, diluted_margin, estimated_samples_to_audit, loser, margin, one_vote_over_count, one_vote_under_count, optimistic_samples_to_audit, other_count, two_vote_over_count, two_vote_under_count, version, winner) VALUES ('NEB', 1, 'City of Wollongong Mayoral', 1.00000000, 5.1374813259579275, 0.19464791, 38, 'GLYKIS Marie', 24767, 0, 0, 38, 0, 0, 0, 1, 'BRADBERY Gordon');
INSERT INTO public.assertion (assertion_type, id, contest_name, current_risk, difficulty, diluted_margin, estimated_samples_to_audit, loser, margin, one_vote_over_count, one_vote_under_count, optimistic_samples_to_audit, other_count, two_vote_over_count, two_vote_under_count, version, winner) VALUES ('NEB', 2, 'City of Wollongong Mayoral', 1.00000000, 15.333815377199326, 0.06521534, 112, 'DORAHY John', 8298, 0, 0, 112, 0, 0, 0, 1, 'BRADBERY Gordon');
INSERT INTO public.assertion (assertion_type, id, contest_name, current_risk, difficulty, diluted_margin, estimated_samples_to_audit, loser, margin, one_vote_over_count, one_vote_under_count, optimistic_samples_to_audit, other_count, two_vote_over_count, two_vote_under_count, version, winner) VALUES ('NEB', 3, 'City of Wollongong Mayoral', 1.00000000, 6.110550833213273, 0.16365137, 45, 'ANTHONY Andrew', 20823, 0, 0, 45, 0, 0, 0, 1, 'BRADBERY Gordon');
INSERT INTO public.assertion (assertion_type, id, contest_name, current_risk, difficulty, diluted_margin, estimated_samples_to_audit, loser, margin, one_vote_over_count, one_vote_under_count, optimistic_samples_to_audit, other_count, two_vote_over_count, two_vote_under_count, version, winner) VALUES ('NEB', 4, 'City of Wollongong Mayoral', 1.00000000, 11.814298978644382, 0.08464319, 87, 'COX Mithra', 10770, 0, 0, 87, 0, 0, 0, 1, 'BRADBERY Gordon');
INSERT INTO public.assertion (assertion_type, id, contest_name, current_risk, difficulty, diluted_margin, estimated_samples_to_audit, loser, margin, one_vote_over_count, one_vote_under_count, optimistic_samples_to_audit, other_count, two_vote_over_count, two_vote_under_count, version, winner) VALUES ('NEN', 5, 'City of Wollongong Mayoral', 1.00000000, 47.72693173293323, 0.02095253, 348, 'BROWN Tania', 2666, 0, 0, 348, 0, 0, 0, 1, 'BRADBERY Gordon');

INSERT INTO public.assertion (assertion_type, id, contest_name, current_risk, difficulty, diluted_margin, estimated_samples_to_audit, loser, margin, one_vote_over_count, one_vote_under_count, optimistic_samples_to_audit, other_count, two_vote_over_count, two_vote_under_count, version, winner) VALUES ('NEB', 6, 'Richmond Valley Mayoral', 1.00000000, 2.302868922865487, 0.43424095, 17, 'HAYES Robert', 5821, 0, 0, 17, 0, 0, 0, 1, 'MUSTOW Robert');

INSERT INTO public.assertion_assumed_continuing (id, assumed_continuing) VALUES (5, 'BROWN Tania');
INSERT INTO public.assertion_assumed_continuing (id, assumed_continuing) VALUES (5, 'BRADBERY Gordon');

INSERT INTO public.generate_assertions_summary (id, contest_name, error, message, version, warning, winner) VALUES (1, 'City of Wollongong Mayoral', '', '', 0, '', 'BRADBERY Gordon');
INSERT INTO public.generate_assertions_summary (id, contest_name, error, message, version, warning, winner) VALUES (2, 'Richmond Valley Mayoral', '', '', 0, '', 'MUSTOW Robert');